.TH ezmlm-queue 1
.SH NAME
ezmlm-queue \- queue messages using qmail-qmqpc, qmail-multi or qmail-queue

.SH SYNOPSIS
.B ezmlm-queue

.SH DESCRIPTION
\fBezmlm-queue\fR is used by ezmlm/ezmlm-idx programs to deliver or queue
messages to be delivered by indimail-mini's \fBqmail-qmqpc\fR(8),
indimail-mta's \fBqmail-multi\fR(8) or \fBqmail-queue\fR(8). It sets
environment variables using \fBenvdir\fR(8) using files in the directory
$HOME/.defaultqueue followed by files in the directory
\fISYSCONFDIR/control/defaultqueue\fR. These environment varables can
configure \fBqmail-qmqpc\fR(8), \fBqmail-multi\fR(8) or
\fBqmail-queue\fR(8).

\fBqmail-multi\fR(8) uses \fBQUEUE_BASE\fR, \fBQUEUE_START\fR and
\fBQUEUE_COUNT\fR to use indimail-mta's multi-queue environment in
QMAIL/queue directory.

\fBqmail-queue\fR(8) uses \fBQUEUEDIR\fR, else it will use the
default queue QMAIL/queue.

\fBqmail-qmqpc\fR(8) uses \fBPORT_QMQP\fR, \fBOUTGOINGIP\fR,
\fBCONTROLDIR\fR environment variables.

\fBezmlm-queue\fR first checks if SYSCONFDIR/control/qmqpservers is
present and uses \fBqmail-qmqpc\fR(8). if \fBqmqpservers\fR is absent, it
will look for \fBqmail-multi\fR(8). If \fBezmlm-queue\fR doesn't find
\fBqmail-multi\fR in /usr/sbin, it tries \fBqmail-queue\fR. It will exit
with 111 exit code if it finds none of the three binaries.

Following programs use \fBezmlm-queue\fR(1).

\fBezmlm-clean\fR(1), \fBezmlm-dispatch\fR(1), \fBezmlm-get\fR(1),
\fBezmlm-manage\fR(1), \fBezmlm-moderate\fR(1), \fBezmlm-reject\fR(1),
\fBezmlm-request\fR(1), \fBezmlm-send\fR(1), \fBezmlm-split\fR(1),
\fBezmlm-store\fR(1), \fBezmlm-warn\fR(1)

You can make the above program to use a different program instead of
\fBezmlm-queue\fR(1), by setting \fBQMAILQUEUE\fR environment variable.

.SH "SEE ALSO"
envdir(8),
qmail-qmqpc(8),
qmail-multi(8),
qmail-queue(8)
