#!/bin/sh
if test -f $HOME/.rpmmacros
then
	topdir=`grep ^%_topdir $HOME/.rpmmacros | awk '{print $2}'`
	if test -n "$topdir"
	then
		rpmbuild=$topdir
	else
		rpmbuild=$HOME/rpmbuild
	fi
else
	rpmbuild=$HOME/rpmbuild
fi
version=$(cat conf-version)
copy_src=0
echo -n "Copy Source Files - "
read key
if [ " $key" = " y" -o " $key" = " Y" ] ; then
	copy_src=1
fi

make -s ezmlm-idx.spec
if [ $? -ne 0 ] ; then
	echo "make failed" 1>&2
	exit 1
fi
if [ $copy_src -eq 1 ] ; then
	cd ..
	if [ -d stage ] ; then
		/bin/rm -rf stage
	fi
	mkdir stage
	if [ $? -ne 0 ] ; then
		exit 1
	fi
	cp -rp ezmlm-idx-$version stage
	if [ $? -ne 0 ] ; then
		exit 1
	fi
	cd stage/ezmlm-idx-$version
	if [ $? -ne 0 ] ; then
		exit 1
	fi
	make -s clean
	make -s distclean
	cd ..
	tar \
		--exclude="ezmlm-idx-$version/.git" \
		--exclude="ezmlm-idx-$version/debian" \
		--exclude="ezmlm-idx-$version/RCS" \
		-cf - ezmlm-idx-"$version" \
			| gzip -c > $rpmbuild/SOURCES/ezmlm-idx-"$version".tar.gz
	cd ..
	/bin/rm -rf stage
else
	cd ..
fi
dist=`uname -r |cut -d . -f4`
if [ $# -gt 0 ] ; then
	release=$1
else
	if [ -f /usr/bin/ezmlm-idx ] ; then
		edist=$(rpm -qf /usr/bin/ezmlm-idx|cut -d- -f4|cut -d. -f3)
		if [ " $dist" = " $edist" ] ; then
			eversion=$(rpm -qf /usr/bin/ezmlm-idx|cut -d- -f3)
			if [ "$eversion" = "$version" ] ; then
				release=$(rpm -qf /usr/bin/ezmlm-idx | cut -d- -f4 | cut -d. -f2)
				release=$(expr $release + 1)
			else
				release=1
			fi
		else
			release=1
		fi
	else
		release=1
	fi
fi
echo -n "Build RPM for ezmlm-idx-"$version"-1."$release" (Y/N) - "
read key
if [ " $key" = " Y" -o " $key" = " y" ] ; then
	tmprel=`cat ezmlm-idx-$version/conf-release 2>/dev/null`
	if [ ! " $tmprel" = " 1.$release" ] ; then
		echo 1.$release > ezmlm-idx-$version/conf-release
		cd ezmlm-idx-$version
		make -s ezmlm-idx.spec
		cp ezmlm-idx.spec /tmp
		cd debian
		make -s
	else
		cp ezmlm-idx-$version/ezmlm-idx.spec /tmp
	fi
	rpmbuild -ba --clean /tmp/ezmlm-idx.spec
	/bin/rm -f /tmp/ezmlm-idx.spec
	build_arch=`rpmbuild --showrc|grep "^build arch" | awk '{print $4}'`
	for i in ezmlm-idx ezmlm-idx-cgi ezmlm-idx-mysql ezmlm-idx-sqlite3 ezmlm-idx-pgsql
	do
		rpm --addsign $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
	done
	rpm --addsign $rpmbuild/SRPMS/ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
	echo -n "RPM lint for ezmlm-idx-"$version"-1."$release" (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		(
		for i in ezmlm-idx ezmlm-idx-cgi ezmlm-idx-mysql ezmlm-idx-sqlite3 ezmlm-idx-pgsql
		do
			echo $i
			rpmlint $rpmbuild/RPMS/$build_arch/$i-"$version"-"1.$release".$dist.$build_arch.rpm
			echo ------------------------
		done
		echo ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
		rpmlint $rpmbuild/SRPMS/ezmlm-idx-"$version"-"1.$release".$dist.src.rpm
		echo ------------------------
		) 2>&1 | less
	fi
fi
if [ $copy_src -eq 1 ] ; then
	echo -n "Remove Source (Y/N) - "
	read key
	if [ " $key" = " Y" -o " $key" = " y" ] ; then
		/bin/rm -f $rpmbuild/SOURCES/ezmlm-idx-"$version".tar.gz
	fi
fi
