name: ezmlm-idx obs trigger

on:
  push:
    paths:
      - '**/ezmlm-idx-x/**'
      - .github/workflows/ezmlm-idx-obs.yml
      - '!**/ezmlm-idx-x/debian/*'
      - '!**/ezmlm-idx-x/ezmlm-idx.spec.template'
      - '!**/doc/*'
      - '!**.md'
      - '!**/ezmlm-idx-freebsd.yml'
      - '!**/ezmlm-idx-c-cpp.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout_ezmlm-idx
      uses: actions/checkout@v2
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: |
        sudo apt-get update; sudo apt-get install libssl-dev libmysqlclient-dev
        cd libqmail; ./default.configure; make; sudo make install-strip
    - name: prepare obs
      run: sudo apt-get update; sudo apt-get install; cd ezmlm-idx-x; ./prepare_obs ezmlm-idx
    - uses: actions/upload-artifact@v2
      with:
        name: ezmlm-idx
        path: |
          ~/*.tar.gz
          ~/*.spec
          ~/*.dsc
    - shell: bash
      name: trigger_obs
      run: |
        mkdir ~/.ssh
        echo "${{secrets.sf_private_key}}" > ~/.private_key
        chmod 600 ~/.private_key
        echo "${{secrets.sf_known_hosts}}" > ~/.ssh/known_hosts
        cd ~
        tar cvfz $GITHUB_WORKSPACE/ezmlm-idx-obs.tar.gz *.tar.gz *.spec *.dsc
        # copy to /home/frs/project/indimail
        scp -q -i ~/.private_key $GITHUB_WORKSPACE/ezmlm-idx-obs.tar.gz  "${{secrets.sf_user}}:${{secrets.sf_upload_path}}"
        rm -f ~/.private_key ~/.ssh/known_hosts $GITHUB_WORKSPACE/ezmlm-idx-obs.tar.gz
