name: ezmlm-idx Ubuntu, Mac OSX CI

on:
  push:
    paths:
      - '**/ezmlm-idx-x/**'
      - .github/workflows/ezmlm-idx-c-cpp.yml
      - '!**/ezmlm-idx-x/debian/*'
      - '!**/ezmlm-idx-x/ezmlm-idx.spec.in'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.host }}-${{ matrix.config.name }}
    runs-on: ${{ matrix.host }}
    strategy:
      fail-fast: false
      matrix:
        host: [ubuntu-latest, macos-latest]
    
    steps:
    - name: extra_packages
      run: |
        if [ "${OS}" = "macos-latest" ]; then brew install automake autoconf libtool pkgconfig openssl mysql; fi
        if [ "${OS}" = "ubuntu-latest" ] ; then sudo apt-get install automake autoconf libtool libssl-dev libmysqlclient-dev; fi
      env:
        OS: ${{ matrix.host }}

    - name: checkout_main
      uses: actions/checkout@v2
      with:
        path: ezmlm-idx
      
    - name: checkout_qmail
      uses: actions/checkout@v2
      with:
        repository: mbhangui/libqmail
        path: libqmail

    - name: install_qmail
      run: cd libqmail;env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib" ./default.configure; env CPPFLAGS="-I/opt/homebrew/Cellar/openssl@3/3.3.0/include" LDFLAGS="-L/opt/homebrew/Cellar/openssl@3/3.3.0/lib" make; sudo make install-strip
    - name: build_ezmlm-idx
      run: |
        cd ezmlm-idx/ezmlm-idx-x
        ./default.configure; ./qmake
      env:
        OS: ${{ matrix.host }}
