name: ezmlm-idx FreeBSD

on:
  push:
    paths:
      - '**/ezmlm-idx-x/**'
      - .github/workflows/ezmlm-idx-freebsd.yml
      - '!**/ezmlm-idx-x/debian/*'
      - '!**/ezmlm-idx-x/ezmlm-idx.spec.in'
      - '!**/*.9'
      - '!**/*.8'
      - '!**/*.5'
      - '!**/*.1'
      - '!**/doc/*'
      - '!**.md'
      - '!**/ezmlm-idx-c-cpp.yml'
      - '!**/ezmlm-idx-obs.yml'
  workflow_dispatch:

jobs:
  testfreebsd:
    runs-on: ubuntu-latest
    name: FreeBSD
    env:
      MYTOKEN : ${{ secrets.MYTOKEN }}
    steps:
    - uses: actions/checkout@v4
      with:
        path: main
    - uses: actions/checkout@v4
      with:
        repository: mbhangui/libqmail
        path: libqmail
    - name: build ezmlm-idx
      id: FreeBSD
      uses: vmactions/freebsd-vm@v1
      with:
        envs: 'MYTOKEN'
        usesh: true
        prepare: pkg install -y curl automake autoconf libtool pkgconf mysql80-server mysql80-client
        run: |
          cd libqmail; ./default.configure; make; make install-strip
          cd ../main/ezmlm-idx-x
          ./default.configure
          ./qmake
